package main

import (
	"archive/zip"
	"bytes"
	"fmt"
	"os"
	"sort"

	"github.com/ripta/unihan/pkg/generate"
)

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	source := "tmp/Unihan_17.0.0.zip"
	if len(args) > 0 {
		source = args[0]
	}

	f, err := os.Open(source)
	if err != nil {
		return err
	}

	defer f.Close()

	fi, err := f.Stat()
	if err != nil {
		return err
	}

	zr, err := zip.NewReader(f, fi.Size())
	if err != nil {
		return fmt.Errorf("open %s: %v", source, err)
	}

	ur, err := generate.ParseUnihanReadings(zr)
	if err != nil {
		return err
	}

	//fmt.Printf("Length: %d\n", len(ur))
	//for k, vs := range ur {
	//	for i, v := range vs {
	//		if len(v) == 0 {
	//			continue
	//		}
	//
	//		fmt.Printf("%U: %s: %v (%d)\n", k, definitions.UnihanReadingKeys[i], v, len(v))
	//	}
	//
	//	break
	//}

	out := &bytes.Buffer{}
	fmt.Fprint(out, "// Code generated by github.com/ripta/unihan/cmd/generate; DO NOT EDIT.\n")
	fmt.Fprint(out, "package data\n\n")
	fmt.Fprint(out, `import "github.com/ripta/unihan/pkg/definitions"`)
	fmt.Fprint(out, "\n\n")
	fmt.Fprint(out, "var UnihanReadings = map[rune]definitions.UnihanReading{\n")

	orderedRunes := make([]int32, 0, len(ur))
	for k := range ur {
		orderedRunes = append(orderedRunes, k)
	}
	sort.Slice(orderedRunes, func(i, j int) bool {
		return orderedRunes[i] < orderedRunes[j]
	})

	for _, k := range orderedRunes {
		fmt.Fprintf(out, "\t%d: {", k)

		vs := ur[k]
		for i, v := range vs {
			fmt.Fprintf(out, "%q", v)
			if i != len(vs)-1 {
				fmt.Fprint(out, ", ")
			} else {
				fmt.Fprint(out, "")
			}
		}
		fmt.Fprint(out, "},\n")
	}
	fmt.Fprint(out, "}\n")

	if len(args) > 1 {
		if err := os.WriteFile(args[1], out.Bytes(), 0644); err != nil {
			return fmt.Errorf("writing to %s: %v", args[1], err)
		}
	}

	return nil
}
